# chaptor 15 정리

## 예외상황

- if 문을 이용한 예외처리
- c++은 try catch, throw로 한다
  
- 실행의 흐름은 try
- 예외 발생하면 throw실행하고 catch 블록 실행
  - try 블록의 나머지 부분 실행 안됨
  - catch 실행하고 종료
  - 예외 발생하지 않으면 try catch 이후 실행

## stack unwinding

- 예외의 발생위치와 처리위치가 다름
  - 호출한 함수 내에서 예외가 발생하면 함수를 호출한 영역으로 예외처리에 대한 책임이 넘어간다
  - 호출한 함수에서 예외가 처리 되지 않으면 함수를 호출한 영역으로 예외 데이터가 넘어간다.

- stack unwinding
  - 예외가 처리되지 않으면 예외 데이터가 함수 호출 순서의 역순으로 전달된다.
  - 함수 호출은 스택 in. 예외 데이터 전달은 스택 out

- 자료형이 일치하지 않아도 예외데이터는 전달
  - throw와 catch의 자료형이 일치하지 않으면
  - 함수를 호출한 영역으로 예외데이터를 전달한다.
  - 자료형이 다른 예외가 발생할 수 있기 때문에 하나의 try 블록에 다수의 catch 블록 추가

- 이러한 예외가 전달 될 수 있다.
  - 명시되지 않은 예외가 있으면 프로그램 종료
  - terminate 실행
  - 프로그래머의 점검 유도

## 예외 클래스

- 예외 객체: 예외 발생을 알리는 데 사용되는 객체
- 예외 클래스: 예외 객체의 생성을 위해 정의된 클래스

- 상속에 의한 예외 전달
  - 유도된 예외 객체의 catch가 먼저 와야한다.
  - 부모의 함수는 자식의 함수이기도 때문이다.

## new 연산자 예외 등 

- bad alloc 16장
- 모든 예외를 처리하는 catch 블록
  - catch(...)
  - 모든 예외가 자료형에 상관없이 전달됨
- 예외 다시 던지기
